#!/bin/sh

# backup home to usb
rsync -aAXvz --ignore-errors --delete --progress \
--exclude Downloads \
--exclude Music \
--exclude Videos \
--exclude torrents \
--exclude .nv \
--exclude .var \
--exclude .cache \
--exclude .dbus \
--exclude .mozilla \
--exclude .local/share/flatpak \
--exclude .local/share/Trash \
/home/djwilcox /var/run/media/djwilcox/backup
